import './globals.css'
import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'

import { config } from '@/app/config'
import { ContextProvider } from '@/app/context'
import Navbar from './components/navbar'
import Sidebar from './components/sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}) {

  const initialState = cookieToInitialState(config, headers().get('cookie'));
  const address = initialState.connections.values().next().value.accounts[0]

  return (
    <html lang="en">
      <body>
        <ContextProvider initialState={initialState}>
        <main>
          <Navbar/>
          <Sidebar/>
          <div className="p-4 sm:ml-64">
            <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 mt-14">
              {children}
            </div>
          </div>
        </main>
        </ContextProvider>
      </body>
    </html>
  )
}